### ISSUE TITLE
artwork-lnf-theme-netrunner-core does not build

### ISSUE THREAD

**Issue by shadeslayer** [netrunner/netrunner-lnf-package#1]
http://dci.pangea.pub/view/Failing/job/stable_stable_netrunner-artwork_artwork-lnf-theme-netrunner-core_bin_amd64/3/console#console-section-1

**Comment by UriHerrera** [comment]
I've modified the cmakelists files but I can't push to this repo and the other one is gone.

**Comment by star-buck** [comment]
@UriHerrera : i sent an invitiation

**Comment by shadeslayer** [comment]
Still failing http://dci.pangea.pub/view/Failing/job/stable_stable_netrunner-artwork_artwork-lnf-theme-netrunner-core_bin_amd64/4/console

**Comment by shadeslayer** [comment]
I've fixed it
